SELECT 
round(SUM(ped.qt) / prod.qtunitcx) as QT_APROX_CX
FROM PCPEDI PED
JOIN PCPRODUT PROD 
ON PED.CODPROD = PROD.CODPROD
WHERE NUMCAR = 182
and prod.codprod = 5550
GROUP BY PED.CODPROD, PROD.DESCRICAO, prod.qtunitcx
ORDER BY PED.CODPROD