SELECT codprod, qt, qtreserv, dtvalidade, datafabricacao, numlote, numlotefab, numtransent, numtransentorig FROM PCLOTE WHERE dtVALIDADE = TO_DATE('31/12/2020', 'DD/MM/YY') and qt > 0;
SELECT * FROM PCLOTE WHERE CODPROD = 14460;

SELECT numbonus, CODPROD, QTENTRADA, dtvalidade, datafabricacao, NUMLOTE, numlotefab FROM pcbonusi WHERE numbonus = 13;

SELECT PEDI.NUMPED, FALTA.NUMPED, PEDI.CODPROD, FALTA.CODPROD, PEDI.QT, FALTA.QT, PEDI.PVENDA, FALTA.PVENDA FROM PCPEDI PEDI, PCFALTA FALTA

WHERE
FALTA.NUMPED = PEDI.NUMPED
AND
FALTA.CODPROD = PEDI.CODPROD
AND
PEDI.PVENDA > FALTA.PVENDA
AND
PEDI.NUMPED = 4000044;

SELECT SUM((PEDI.QT*PEDI.PVENDA)), ped.vlatend, ped.vltotal 
FROM PCPEDI PEDI, PCPEDC PED 

WHERE PEDI.NUMPED = PED.NUMPED AND PEDI.NUMPED = 4000044

group by ped.vlatend, ped.vltotal;

