SELECT 
       -- DADOS NFE --
       NF.NUMNOTA AS NUMERO_NFE,
       NF.DTENTREGA AS DT_ENTREGA,
       NF.CODCLI AS COD_CLIENTE,
       
       
       -- DADOS CLIENTE --
       CLIENTE.CLIENTE AS NOME_CLIENTE,
       cliente.fantasia as fantasia,
       cliente.enderent AS ENDERECO_ENTREGA,
       cliente.bairroent AS BAIRRO_ENTREGA,
       cliente.municent AS CIDADE,
       CLIENTE.CGCENT AS "CNPJ / CPF", 
       CLIENTE.ESTENT AS UF,
       
       -- DADOS MOVIMENTO --
       MOVIMENTO.CODPROD, 
       PRODUTOS.DESCRICAO,
       movimento.codusur AS COD_VENDEDOR,
       vendedores.nome AS NOME_VENDEDOR,
       
       -- CALCULO DE TOTAIS E CAIXAS --
       LPAD(MOVIMENTO.QT||' - '||PRODUTOS.UNIDADE,12,' ') as QT_TOTAL,
       LPAD(trunc((movimento.qt) / produtos.qtunitcx),5,' ')||' - '||produtos.unidademaster as TOTAL_CAIXAS,
       CASE
          WHEN 'PC' IN (SELECT TMPEMB.UNIDADE FROM PCEMBALAGEM TMPEMB WHERE TMPEMB.CODPROD = MOVIMENTO.CODPROD)
            THEN LPAD(ROUND(MOD((movimento.qt), produtos.qtunitcx) / (SELECT TMPEMB.QTUNIT FROM PCEMBALAGEM TMPEMB WHERE TMPEMB.CODPROD = MOVIMENTO.CODPROD AND TMPEMB.UNIDADE = 'PC')),3,' ')
          ELSE LPAD(NVL(MOD((movimento.qt), produtos.qtunitcx) / (SELECT TMPEMB.QTUNIT FROM PCEMBALAGEM TMPEMB WHERE TMPEMB.CODPROD = MOVIMENTO.CODPROD AND TMPEMB.UNIDADE = 'UN'),0),3,' ')
       END ||' - '||RPAD(PRODUTOS.EMBALAGEM,13,' ') as UNIDADES, 
       
       
       -- DADOS CARREGAMENTO --
       CARREGAMENTO.CODMOTORISTA,
       EMPREGADOS.NOME MOTORISTA,
       CARREGAMENTO.CODFUNCAJUD AS COD_AJUDANTE,
       AJUDANTES.NOME AS NOME_AJUDANTE,
       CARREGAMENTO.NUMCAR, 
       EMPREGADOS.CPF,
      (SELECT  count(*) from pcnfsaid where numcar in(:NUMCAR) and (dtcancel is null or dtdevol is  null)) as numero_de_notas,
      (SELECT COUNT(CLI.CODCLI)
       FROM PCCLIENT CLI
       WHERE CLI.CODCLI IN 
       (SELECT NF.CODCLI FROM PCNFSAID NF WHERE NUMCAR IN(:NUMCAR) AND (dtcancel is null or dtdevol is  null))) as numero_de_clientes
       

FROM  
PCMOV MOVIMENTO,
PCEMBALAGEM EMBALAGEM,
PCPRODUT PRODUTOS, 
PCNFSAID NF, 
PCCLIENT CLIENTE, 
PCCARREG CARREGAMENTO, 
PCEMPR EMPREGADOS,
PCUSUARI VENDEDORES,
PCEMPR AJUDANTES

WHERE MOVIMENTO.CODPROD = PRODUTOS.CODPROD
AND   MOVIMENTO.CODAUXILIAR = EMBALAGEM.CODAUXILIAR

AND   MOVIMENTO.NUMCAR IN (:NUMCAR)
AND   MOVIMENTO.NUMTRANSVENDA = NF.NUMTRANSVENDA
AND   MOVIMENTO.CODCLI = CLIENTE.CODCLI
AND   MOVIMENTO.NUMCAR = CARREGAMENTO.NUMCAR
AND   CARREGAMENTO.CODMOTORISTA = EMPREGADOS.MATRICULA(+)
AND   MOVIMENTO.CODUSUR = VENDEDORES.CODUSUR
AND   CARREGAMENTO.CODFUNCAJUD = AJUDANTES.MATRICULA(+)

AND   NF.DTCANCEL IS NULL
AND    NF.CONDVENDA <> 4
AND    MOVIMENTO.QT > 0


ORDER BY CLIENTE.CLIENTE, NF.NUMNOTA, MOVIMENTO.CODPROD
